### PR TITLE
Update flutter sdk

### PR DESCRIPTION
**Pull request by OsmanBrito**
Update flutter sdk, solving problem with support to dart sdk version above 2.0.0

### CODE REVIEW

**Comment by galangptrm** [comment]
it still does'nt solve the problem :)

**Comment by galangptrm** [comment]
I put this on my pubspec.yaml

version: 1.0.0+1
environment:
  sdk: ">=1.19.0 <3.0.0"

dependencies:
  speech_recognition: ^0.2.0+1

got the same error :
The current Dart SDK version is 2.1.0-dev.3.1.flutter-760a9690c2.

Because qiraat_beta depends on speech_recognition >=0.2.0+1 which requires SDK version <2.0.0, version solving failed.
pub get failed (1)

**Comment by OsmanBrito** [comment]
To solve the problem in your project you must change MainActivity and add speech_recognition.dart

MainActivity.java
```java

import android.content.Intent;
import android.os.Bundle;
import android.speech.RecognitionListener;
import android.speech.RecognizerIntent;
import android.speech.SpeechRecognizer;
import android.util.Log;
import io.flutter.app.FlutterActivity;
import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugins.GeneratedPluginRegistrant;

import java.util.ArrayList;
import java.util.Locale;

public class MainActivity extends FlutterActivity implements RecognitionListener {

  private static final String SPEECH_CHANNEL = "speech_recognition";
  private static final String LOG_TAG = "SYTODY";
  private SpeechRecognizer speech;
  private MethodChannel speechChannel;
  String transcription = "";
  private boolean cancelled = false;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);

    speech = SpeechRecognizer.createSpeechRecognizer(getApplicationContext());
    speech.setRecognitionListener(this);

    final Intent recognizerIntent = new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);
    recognizerIntent.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL, RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);
    recognizerIntent.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS, true);
    recognizerIntent.putExtra(RecognizerIntent.EXTRA_MAX_RESULTS, 3);

    speechChannel = new MethodChannel(getFlutterView(), SPEECH_CHANNEL);
    speechChannel.setMethodCallHandler(new MethodChannel.MethodCallHandler() {
      @Override
      public void onMethodCall(MethodCall call, MethodChannel.Result result) {
        switch (call.method) {
        case "speech.activate":
          result.success(true); // on Android 6- permissions were given during installation
          speechChannel.invokeMethod("speech.onCurrentLocale", "pt_BR");
          break;
        case "speech.listen":
          recognizerIntent.putExtra(RecognizerIntent.EXTRA_LANGUAGE, getLocale(call.arguments.toString()));
          cancelled = false;
          speech.startListening(recognizerIntent);
          result.success(true);
          break;
        case "speech.start":
          recognizerIntent.putExtra(RecognizerIntent.EXTRA_LANGUAGE, getLocale(call.arguments.toString()));
          cancelled = false;
          speech.startListening(recognizerIntent);
          result.success(true);
          break;
        case "speech.cancel":
          speech.stopListening();
          cancelled = true;
          result.success(true);
          break;
        case "speech.stop":
          speech.stopListening();
          cancelled = false;
          result.success(true);
          break;
        default:
          result.notImplemented();
        }
      }
    });
  }

  private Locale getLocale(String code) {
    String[] localeParts = code.split("_");
    return new Locale(localeParts[0], localeParts[1]);
  }

  @Override
  public void onReadyForSpeech(Bundle params) {
    Log.d("SYDOTY", "onReadyForSpeech");
    speechChannel.invokeMethod("speech.onSpeechAvailability", true);
  }

  @Override
  public void onBeginningOfSpeech() {
    Log.d("SYDOTY", "onRecognitionStarted");
    transcription = "";
    speechChannel.invokeMethod("speech.onRecognitionStarted", null);
  }

  @Override
  public void onRmsChanged(float rmsdB) {
    Log.d("SYDOTY", "onRmsChanged : " + rmsdB);
  }

  @Override
  public void onBufferReceived(byte[] buffer) {
    Log.d("SYDOTY", "onBufferReceived");
  }

  @Override
  public void onEndOfSpeech() {
    Log.d("SYDOTY", "onEndOfSpeech");
    speechChannel.invokeMethod("speech.onRecognitionComplete", transcription);
  }

  @Override
  public void onError(int error) {
    Log.d("SYDOTY", "onError : " + error);
    speechChannel.invokeMethod("speech.onSpeechAvailability", false);
    speechChannel.invokeMethod("speech.onError", error);
  }

  @Override
  public void onPartialResults(Bundle partialResults) {
    Log.d("SYDOTY", "onPartialResults...");
    Log.i(LOG_TAG, "onResults");
    ArrayList<String> matches = partialResults.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);
    transcription = matches.get(0);
    sendTranscription(false);

  }

  @Override
  public void onResults(Bundle results) {
    Log.d(LOG_TAG, "onResults...");
    ArrayList<String> matches = results.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);
    String text = "";
    transcription = matches.get(0);
    Log.d(LOG_TAG, "onResults -> " + transcription);
    sendTranscription(true);
  }

  private void sendTranscription(boolean isFinal) {
    speechChannel.invokeMethod(isFinal ? "speech.onRecognitionComplete" : "speech.onSpeech", /* cancelled ? "" : */ transcription);
  }

  @Override
  public void onEvent(int eventType, Bundle params) {
    Log.d("SYDOTY", "onEvent : " + eventType);
  }

}
```

speech_recognition.dart
```dart
import 'dart:async';

import 'dart:ui';
import 'package:flutter/services.dart';

typedef void AvailabilityHandler(bool result);
typedef void StringResultHandler(String text);

/// the channel to control the speech recognition
class SpeechRecognition {
  static const MethodChannel _channel =
      const MethodChannel('speech_recognition');

  static final SpeechRecognition _speech = new SpeechRecognition._internal();

  factory SpeechRecognition() => _speech;

  SpeechRecognition._internal() {
    _channel.setMethodCallHandler(_platformCallHandler);
  }

  AvailabilityHandler availabilityHandler;

  StringResultHandler currentLocaleHandler;
  StringResultHandler recognitionResultHandler;

  VoidCallback recognitionStartedHandler;

  VoidCallback recognitionCompleteHandler;

  /// ask for speech  recognizer permission
  Future activate() => _channel.invokeMethod("speech.activate");

  /// start listening
  Future listen({String locale}) =>
      _channel.invokeMethod("speech.listen", locale);

  Future cancel() => _channel.invokeMethod("speech.cancel");

  Future stop() => _channel.invokeMethod("speech.stop");

  Future _platformCallHandler(MethodCall call) async {
    print("_platformCallHandler call ${call.method} ${call.arguments}");
    switch (call.method) {
      case "speech.onSpeechAvailability":
        availabilityHandler(call.arguments);
        break;
      case "speech.onCurrentLocale":
        currentLocaleHandler(call.arguments);
        break;
      case "speech.onSpeech":
        recognitionResultHandler(call.arguments);
        break;
      case "speech.onRecognitionStarted":
        recognitionStartedHandler();
        break;
      case "speech.onRecognitionComplete":
        recognitionCompleteHandler();
        break;
      default:
        print('Unknowm method ${call.method} ');
    }
  }

  // define a method to handle availability / permission result
  void setAvailabilityHandler(AvailabilityHandler handler) =>
      availabilityHandler = handler;

  // define a method to handle recognition result
  void setRecognitionResultHandler(StringResultHandler handler) =>
      recognitionResultHandler = handler;

  // define a method to handle native call
  void setRecognitionStartedHandler(VoidCallback handler) =>
      recognitionStartedHandler = handler;

  // define a method to handle native call
  void setRecognitionCompleteHandler(VoidCallback handler) =>
      recognitionCompleteHandler = handler;

  void setCurrentLocaleHandler(StringResultHandler handler) =>
      currentLocaleHandler = handler;
}
```

**Comment by CarsonHolzheimer** [comment]
@OsmanBrito Are you suggesting not to use the dependency at all? This won't work with iOS

**Comment by Poeticode** [comment]
I was able to get it working on Android (no iOS to test just yet) with alescdb's fork. Under `dependencies` in your pubspec.yaml, simply add:
```
speech_recognition:
      git:
        url: git://github.com/alescdb/speech_recognition.git
```

**Pull request closed without merging**
